import { readFileSync, writeFileSync } from 'node:fs'
import { buildSeedSql } from '../../shared/utils/exerciseSeedSql'
import type { SeedEntry } from '../../shared/utils/exerciseSeedMap'
import { CATALOGUE_BEGIN, CATALOGUE_END, CATALOGUE_FILE, catalogueBounds } from './catalogueBlock'

const PINNED_COMMIT = 'a859101d633a01c4a1a920d6a8ce41dabba0705f'
const SOURCE_URL = `https://raw.githubusercontent.com/yuhonas/free-exercise-db/${PINNED_COMMIT}/dist/exercises.json`

const response = await fetch(SOURCE_URL)
if (!response.ok) throw new Error(`fetch failed: ${response.status} ${response.statusText}`)
const entries = (await response.json()) as SeedEntry[]
entries.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))

const sql = buildSeedSql(entries)
const header
  = `${CATALOGUE_BEGIN} generated by \`bun exercises:seed\` from free-exercise-db@${PINNED_COMMIT} (${entries.length} exercises)\n`
const migration = readFileSync(CATALOGUE_FILE, 'utf8')
const { start, end } = catalogueBounds(migration)
writeFileSync(CATALOGUE_FILE, migration.slice(0, start) + header + sql + '\n' + CATALOGUE_END + migration.slice(end))
console.log(`wrote ${CATALOGUE_FILE} (${entries.length} exercises)`)
